#ifndef NEXUS_CONFIG_H_
#define NEXUS_CONFIG_H_

#define BACKEND_DEFAULT_PORT       8001
#define BACKEND_DEFAULT_RPC_PORT   8002
#define FRONTEND_DEFAULT_PORT      9001
#define FRONTEND_DEFAULT_RPC_PORT  9002
#define SCHEDULER_DEFAULT_PORT     10001
#define BEACON_INTERVAL_SEC        5
#define EPOCH_INTERVAL_SEC         30

#endif // NEXUS_CONFIG_H_
