USE_DARKNET := 1
# USE_CAFFE and USE_CAFFE2 cannot be set to 1 at the same time
USE_CAFFE2 := 1
USE_CAFFE := 0
USE_TENSORFLOW := 1
USE_GPU := 1

CUDA_PATH ?= /usr/local/cuda
CUDNN_PATH ?= /usr/local/cuda